id: I12D6D390
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:08:46+00:00'
last_modified: '2022-06-07T20:53:22.829609+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23650
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དཔལ་ལྡན་ས་སྐྱ་པའི་ལུགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C7F:
      image_group_id: I2367
      title: ''
      total_pages: 560
      order: 1
      base_file: 4C7F.txt
    '3333':
      image_group_id: I2368
      title: ''
      total_pages: 426
      order: 2
      base_file: 3333.txt
    9B89:
      image_group_id: I2369
      title: ''
      total_pages: 506
      order: 3
      base_file: 9B89.txt
    9A2C:
      image_group_id: I2370
      title: ''
      total_pages: 362
      order: 4
      base_file: 9A2C.txt
    F145:
      image_group_id: I2371
      title: ''
      total_pages: 460
      order: 5
      base_file: F145.txt
    9DA9:
      image_group_id: I2372
      title: ''
      total_pages: 474
      order: 6
      base_file: 9DA9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
