id: I12D6D390
legacy_id: P004184
ocr_import_info:
  bdrc_scan_id: W23650
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T17:05:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:34:48.601283+00:00'
last_modified: 2022-09-02 09:37:21.404144
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23650
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23650
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་དཔལ་ལྡན་ས་སྐྱ་པའི་ལུགས།
statistics:
  ocr_word_mean_confidence_index: 0.745130649152117
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I2367:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2367
      total_pages: 560
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2367.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7601406901330784
    legacy_id: v001
  I2370:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2370
      total_pages: 362
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2370.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7262783702719086
    legacy_id: v004
  I2368:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2368
      total_pages: 426
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2368.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7532496110678712
    legacy_id: v002
  I2369:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2369
      total_pages: 506
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2369.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7380489099413251
    legacy_id: v003
  I2372:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2372
      total_pages: 474
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2372.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.759554987029416
    legacy_id: v006
  I2371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2371
      total_pages: 460
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2371.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7252444627426208
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
